name: ci

on:
  push:
    branches:
      - multi-arch-pipeline

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: openchoreo/backstage-plugins

# Avoid running multiple builds for the same commit
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Determine image tag
        id: tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # Extract tag (keep 'v' prefix for Docker images)
            TAG=${GITHUB_REF#refs/tags/}
            echo "IMAGE_TAG=${TAG#v}" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "IMAGE_TAG=${TAG}" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_TAG=latest-dev" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./packages/backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.IMAGE_TAG }}
